services:
  db:
    image: mariadb:12.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ogspy
      MYSQL_USER: ogspy
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ogspy-net

  ogspy-web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - "..:/var/www/html"
    networks:
      - ogspy-net

networks:
  ogspy-net:
    driver: bridge

volumes:
  db_data:
    driver: local
