INSERT INTO `ogspy_config` (`name`, `value`)
VALUES ('allied', ''),
       ('ally_protection', ''),
       ('debug_log', '0'),
       ('default_skin', 'skin/OGSpy_skin/'),
       ('disable_ip_check', '1'),
       ('keeprank_criterion', 'day'),
       ('last_maintenance_action', '0'),
       ('max_battlereport', '10'),
       ('max_favorites', '20'),
       ('max_favorites_spy', '10'),
       ('max_keeplog', '7'),
       ('max_keeprank', '30'),
       ('max_keepspyreport', '30'),
       ('max_spyreport', '10'),
       ('reason', ''),
       ('servername', 'Cartographie'),
       ('server_active', '1'),
       ('session_time', '30'),
       ('url_forum', 'https://forum.ogsteam.eu/'),
       ('log_phperror', '0'),
       ('block_ratio', '0'),
       ('ratio_limit', '0'),
       ('config_cache', '3600'),
       ('mod_cache', '604800'),
       ('ddr', '1'),
       ('astro_strict', '1'),
       ('donutSystem', '1'),
       ('donutGalaxy', '1'),
       ('speed_fleet_peaceful', '1'),
       ('speed_fleet_war', '1'),
       ('speed_fleet_holding', '1'),
       ('speed_research_divisor', '1'),
       ('enable_stat_view', '1'),
       ('enable_members_view', '0'),
       ('portee_missil', '1'),
       ('enable_register_view', '0'),
       ('register_forum', ''),
       ('register_alliance', ''),
       ('galaxy_by_line_stat', '9'),
       ('system_by_line_stat', '10'),
       ('galaxy_by_line_ally', '9'),
       ('system_by_line_ally', '10'),
       ('color_ally', 'Magenta_Yellow_Red'),
       ('nb_colonnes_ally', '3'),
       ('open_user', ''),
       ('open_admin', ''),
       ('mail_active', '0'),
       ('mail_smtp_use', '0'),
       ('mail_smtp_server', ''),
       ('mail_smtp_secure', '0'),
       ('mail_smtp_host', ''),
       ('mail_smtp_port', ''),
       ('mail_smtp_username', ''),
       ('mail_smtp_password', ''),
       ('num_of_galaxies', '9'),
       ('num_of_systems', '499'),
       ('speed_uni', '1'),
       ('version', '4.0.0-dev');


INSERT INTO `ogspy_group`
VALUES (1, 'Standard', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1');

INSERT INTO `ogspy_user` (`id`, `name`, `password_s`, `regdate`, `active`, `admin`, `pwd_change`) VALUES (1, 'ogsteam', '$2y$10$z.6/280zsg65IoOJ/wmOC.cHIWFnKFE8TaY7JSr0DH3fnQsxg7rRW', '1567070548', '1', '1',  0);
INSERT INTO `ogspy_user_group` (`group_id`, `user_id`) VALUES (1, 1);
