name: Docker Image OGSPY

on:
  push:
    branches: [ feature/github_action ]
  pull_request:
    branches: [ feature/github_action ]
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: if [ $(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g") != ${GITHUB_REF} ]; then TAG="latest"; fi;
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file .docker/Dockerfile --tag $IMAGE_NAME:${GITHUB_SHA}
    - name: Docker Login
      if: success()
      #run:  docker login -u ${{ secrets.DOCKER_HUB_USER }} -p "${{ secrets.DOCKER_HUB_PASSWORD }}" ${{ secrets.DOCKER_REGISTRY_URL }}
      run : echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin ${{ secrets.DOCKER_REGISTRY_URL }}
       # docker push docker.pkg.github.com/repoowner/repo_name/image_name:tag

    - name: Push image
      if: success()
      run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/ogsteam/ogspy/$IMAGE_NAME:${GITHUB_SHA} 
