name: Docker Image OGSPY

on:
  push:
    branches: 
    - feature/github_action
    - release/*
    - master
  pull_request:
    branches: [ develop ]
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: why

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    - name: Test
      run: echo "${BRANCH_NAME}"

    - name: Docker Login
      if: success()
      run : echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin ${{ secrets.DOCKER_REGISTRY_URL }}
      
    - name: Build the Docker image
      if: success()
      run: docker build . --file .docker/Dockerfile --tag ${{ secrets.DOCKER_REGISTRY_URL }}/ogsteam/ogspy/develop:latest

    - name: Push image
      if: success()
      run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/ogsteam/ogspy/develop:latest
