name: Docker Image OGSPY

on:
  push:
    branches: [ feature/github_action ]
  pull_request:
    branches: [ feature/github_action ]
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: why
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      if: success()
      #run:  docker login -u ${{ secrets.DOCKER_HUB_USER }} -p "${{ secrets.DOCKER_HUB_PASSWORD }}" ${{ secrets.DOCKER_REGISTRY_URL }}
      run : echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin ${{ secrets.DOCKER_REGISTRY_URL }}
       # docker push docker.pkg.github.com/repoowner/repo_name/image_name:tag
      
    - name: Build the Docker image
      if: success()
      run: docker build . --file .docker/Dockerfile --tag ${{ secrets.DOCKER_REGISTRY_URL }}/ogsteam/ogspy/develop:latest

    - name: Push image
      if: success()
      run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/ogsteam/ogspy/develop:latest
