name: Docker Image OGSPY

on:
  push:
    branches: [ feature/github_action ]
  pull_request:
    branches: [ feature/github_action ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file .docker/Dockerfile
    - name: Dockerize
      if: success()
      uses:  manusa/actions-publish-docker@master
      with:
        name: ogsteam/ogspy
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tag script: |
            return context.ref
            .replace('refs/heads/
            .replace('refs/tags/'
            .replace('refs/pull/'
            .replace(/\//g, '_')
            .replace(/#/g, '');:  
